---
- name: Télécharger Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extraire Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Créer un lien symbolique vers /opt/prometheus
  file:
    src: /opt/prometheus-2.52.0.linux-amd64
    dest: /opt/prometheus
    state: link
    force: yes

- name: Créer le service systemd pour Prometheus
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      ExecStart=/opt/prometheus/prometheus \
        --config.file=/opt/prometheus/prometheus.yml \
        --web.listen-address=0.0.0.0:9090
      Restart=always

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Recharger systemd
  systemd:
    daemon_reload: yes

- name: Activer et démarrer Prometheus
  systemd:
    name: prometheus
    enabled: true
    state: started

- name: Display how to connect to the Grafana server instance
  ansible.builtin.debug:
    msg: "Connect at http://{{ external_ip }}:9090"