#SPDX-License-Identifier: MIT-0
---
# tasks file for loki

- name: Installer unzip pour décompresser les fichiers zip
  apt:
    name: unzip
    state: present
    update_cache: true

- name: Download Loki
  get_url:
    url: https://github.com/grafana/loki/releases/download/v2.9.4/loki-linux-amd64.zip
    dest: /tmp/loki.zip

- name: Unzip Loki
  unarchive:
    src: /tmp/loki.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: Make Loki executable
  file:
    path: /usr/local/bin/loki-linux-amd64
    mode: '0755'

- name: Create Loki config file
  copy:
    dest: /etc/loki-config.yaml
    content: |
      auth_enabled: false
      server:
        http_listen_port: 3100
      ingester:
        lifecycler:
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
        chunk_idle_period: 5m
        max_chunk_age: 1h
        chunk_retain_period: 30s
        max_transfer_retries: 0
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
      storage_config:
        boltdb_shipper:
          active_index_directory: /tmp/loki/index
          cache_location: /tmp/loki/index_cache
          shared_store: filesystem
        filesystem:
          directory: /tmp/loki/chunks
      limits_config:
        enforce_metric_name: false
      chunk_store_config:
        max_look_back_period: 0s
      table_manager:
        retention_deletes_enabled: true
        retention_period: 7d

- name: Create systemd service for Loki
  copy:
    dest: /etc/systemd/system/loki.service
    content: |
      [Unit]
      Description=Loki
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/loki-linux-amd64 -config.file=/etc/loki-config.yaml
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Enable and start Loki
  systemd:
    name: loki
    enabled: true
    state: started
